'\" t
.\"     Title: xpstojpeg
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 08/09/2017
.\"    Manual: XPS Tools
.\"    Source: XPS Tools
.\"  Language: English
.\"
.TH "XPSTOJPEG" "1" "08/09/2017" "XPS Tools" "XPS Tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xpstojpeg \- XPS to JPEG converter
.SH "SYNOPSIS"
.HP \w'\fBxpstojpeg\fR\ 'u
\fBxpstojpeg\fR [\fIOPTION\fR...] FILE [\fIOUTPUT\ FILE\fR]
.SH "DESCRIPTION"
.PP
\fBxpstojpeg\fR
converts XPS documents to JPEG format\&.
\fBxpstojpeg\fR
reads the XPS file,
\fIFILE\fR, and writes a JPEG file per page with the page number and file type appended to
\fIOUTPUT FILE\fR\&. If
\fIOUTPUT FILE\fR
is not specified "page" will be used\&.
.SH "OPTIONS"
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Show help options\&.
.RE
.PP
\fB\-d\fR \fIDOCUMENT\fR, \fB\-\-document\fR=\fIDOCUMENT\fR
.RS 4
The document inside the XPS file to convert\&. By default, the first document of the XPS file is used\&.
.RE
.PP
\fB\-f\fR \fIPAGE\fR, \fB\-\-first\fR=\fIPAGE\fR
.RS 4
The first page to convert\&.
.RE
.PP
\fB\-l\fR \fIPAGE\fR, \fB\-\-last\fR=\fIPAGE\fR
.RS 4
The last page to convert\&.
.RE
.PP
\fB\-o\fR, \fB\-\-odd\fR
.RS 4
Convert only odd pages\&.
.RE
.PP
\fB\-e\fR, \fB\-\-even\fR
.RS 4
Convert only even pages\&.
.RE
.PP
\fB\-r\fR \fIRESOLUTION\fR, \fB\-\-resolution\fR=\fIRESOLUTION\fR
.RS 4
Horizontal and vertical resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-\-rx\fR=\fIRESOLUTION\fR
.RS 4
Horizontal resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-\-ry\fR=\fIRESOLUTION\fR
.RS 4
Vertical resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-x\fR \fIX\fR, \fB\-\-crop\-x\fR=\fIX\fR
.RS 4
The x\-coordinate of the crop area top left corner\&.
.RE
.PP
\fB\-y\fR \fIY\fR, \fB\-\-crop\-y\fR=\fIY\fR
.RS 4
The y\-coordinate of the crop area top left corner\&.
.RE
.PP
\fB\-w\fR \fIWIDTH\fR, \fB\-\-crop\-width\fR=\fIWIDTH\fR
.RS 4
The width of crop area\&.
.RE
.PP
\fB\-h\fR \fIHEIGHT\fR, \fB\-\-crop\-height\fR=\fIHEIGHT\fR
.RS 4
The height of crop area\&.
.RE
.SH "BUGS"
.PP
Please send bug reports to
\m[blue]\fBhttps://bugzilla\&.gnome\&.org/enter_bug\&.cgi?product=libgxps\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBxpstopng\fR(1)
\fBxpstopdf\fR(1)
\fBxpstops\fR(1)
\fBxpstosvg\fR(1)
