'\" t
.\"     Title: xpstops
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/13/2015
.\"    Manual: XPS Tools
.\"    Source: XPS Tools
.\"  Language: English
.\"
.TH "XPSTOPS" "1" "08/13/2015" "XPS Tools" "XPS Tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xpstops \- XPS to PostScript converter
.SH "SYNOPSIS"
.HP \w'\fBxpstops\fR\ 'u
\fBxpstops\fR [\fIOPTION\fR...] FILE [\fIOUTPUT\ FILE\fR]
.SH "DESCRIPTION"
.PP
\fBxpstops\fR
converts XPS documents to PostScript format\&.
\fBxpstops\fR
reads the XPS file,
\fIFILE\fR, and writes a PostScript file,
\fIOUTPUT FILE\fR\&. If
\fIOUTPUT FILE\fR
is not specified the output filename will be derived from the
\fIOUTPUT FILE\fR
filename\&.
.SH "OPTIONS"
.PP
\fB\-?\fR, \fB\-\-help\fR
.RS 4
Show help options\&.
.RE
.PP
\fB\-d\fR \fIDOCUMENT\fR, \fB\-\-document\fR=\fIDOCUMENT\fR
.RS 4
The document inside the XPS file to convert\&. By default, the first document of the XPS file is used\&.
.RE
.PP
\fB\-f\fR \fIPAGE\fR, \fB\-\-first\fR=\fIPAGE\fR
.RS 4
The first page to convert\&.
.RE
.PP
\fB\-l\fR \fIPAGE\fR, \fB\-\-last\fR=\fIPAGE\fR
.RS 4
The last page to convert\&.
.RE
.PP
\fB\-o\fR, \fB\-\-odd\fR
.RS 4
Convert only odd pages\&.
.RE
.PP
\fB\-e\fR, \fB\-\-even\fR
.RS 4
Convert only even pages\&.
.RE
.PP
\fB\-r\fR \fIRESOLUTION\fR, \fB\-\-resolution\fR=\fIRESOLUTION\fR
.RS 4
Horizontal and vertical resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-\-rx\fR=\fIRESOLUTION\fR
.RS 4
Horizontal resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-\-ry\fR=\fIRESOLUTION\fR
.RS 4
Vertical resolution in PPI (Pixels Per Inch)\&. The default is 150 PPI\&.
.RE
.PP
\fB\-x\fR \fIX\fR, \fB\-\-crop\-x\fR=\fIX\fR
.RS 4
The x\-coordinate of the crop area top left corner\&.
.RE
.PP
\fB\-y\fR \fIY\fR, \fB\-\-crop\-y\fR=\fIY\fR
.RS 4
The y\-coordinate of the crop area top left corner\&.
.RE
.PP
\fB\-w\fR \fIWIDTH\fR, \fB\-\-crop\-width\fR=\fIWIDTH\fR
.RS 4
The width of crop area\&.
.RE
.PP
\fB\-h\fR \fIHEIGHT\fR, \fB\-\-crop\-height\fR=\fIHEIGHT\fR
.RS 4
The height of crop area\&.
.RE
.PP
\fB\-\-level2\fR
.RS 4
Generate Level 2 PostScript\&. Level 2 supports color images and image compression\&.
.RE
.PP
\fB\-\-level3\fR
.RS 4
Generate Level 3 PostScript\&. This enables all Level 2 features plus shading patterns and masked images\&. This is the default setting\&.
.RE
.PP
\fB\-\-eps\fR
.RS 4
Generate an Encapsulated PostScript (EPS) file\&.
.RE
.PP
\fB\-\-paper\fR=\fIPAPER\fR
.RS 4
Set the paper size to one of "A0", "A1", "A2", "A3", "A4", "A5", "B4", "B5", "Letter", "Tabloid", "Ledger", "Legal", "Statement", "Executive", "Folio", "Quarto", "10x14"\&.
.RE
.PP
\fB\-\-duplex\fR
.RS 4
Adds the %%IncludeFeature: *Duplex DuplexNoTumble DSC comment to the PostScript file\&. This tells the print manager to enable duplexing\&.
.RE
.PP
\fB\-\-paper\-width\fR=\fIWIDTH\fR
.RS 4
The paper width\&.
.RE
.PP
\fB\-\-paper\-height\fR=\fIHEIGHT\fR
.RS 4
The paper height\&.
.RE
.PP
\fB\-\-expand\fR
.RS 4
Expand pages smaller than the paper to fill the paper\&. By default, pages are not scaled\&.
.RE
.PP
\fB\-\-no\-shrink\fR
.RS 4
Don\*(Aqt scale pages which are larger than the paper\&. By default, pages larger than the paper are shrunk to fit\&.
.RE
.PP
\fB\-\-no\-center\fR
.RS 4
Don\*(Aqt center on the paper pages smaller than the paper (after any scaling)\&. By default, pages smaller than the paper are aligned to the lower\-left corner\&.
.RE
.SH "BUGS"
.PP
Please send bug reports to
\m[blue]\fBhttps://bugzilla\&.gnome\&.org/enter_bug\&.cgi?product=libgxps\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBxpstojpeg\fR(1)\fBxpstopng\fR(1)\fBxpstopdf\fR(1)\fBxpstosvg\fR(1)
